#!/usr/bin/env bash

device_num=${1-0}
model_name="${2:-transformer}"
data_encoding="${3:-bra}"

config_file="${model_name}_${data_encoding}.yaml"

echo "-------------------------------------------"
echo "Starting test experiment"
echo "device: $device_num"
echo "model: $model_name"
echo "data encoding: $data_encoding"
echo "config file: $config_file"
echo "-------------------------------------------"

echo "-------------------------------------------"
echo "Starting test experiment"
echo "-------------------------------------------"

CUDA_VISIBLE_DEVICES=$device_num \
HYDRA_FULL_ERROR=1 \
uv run run_test.py +experiments/who_is_alyx="$config_file"
